// Source: http://www.osdever.net/documents/partitiontypes.php

const char *system_ids[256] = {
	/* 0x0 */ "Unknown",
	/* 0x1 */ "DOS 12-bit fat",
	/* 0x2 */ "XENIX root",
	/* 0x3 */ "XENIX /usr",
	/* 0x4 */ "DOS 3.0+ 16-bit FAT (up to 32M)",
	/* 0x5 */ "DOS 3.3+ Extended Partition",
	/* 0x6 */ "DOS 3.31+ 16-bit FAT (over 32M)",
	/* 0x7 */ "QNX2.x (pre-1988)",
	/* 0x8 */ "QNX 1.x and 2.x ('qny')",
	/* 0x9 */ "QNX 1.x and 2.x ('qnz')",
	/* 0xa */ "OPUS",
	/* 0xb */ "WIN95 OSR2 32-bit FAT",
	/* 0xc */ "WIN95 OSR2 32-bit FAT, LBA-mapped",
	/* 0xd */ "Unknown",
	/* 0xe */ "WIN95: DOS 16-bit FAT, LBA-mapped",
	/* 0xf */ "WIN95: Extended partition, LBA-mapped",
	/* 0x10 */ "OPUS (?)",
	/* 0x11 */ "Hidden DOS 12-bit FAT",
	/* 0x12 */ "Compaq config partition",
	/* 0x13 */ "Unknown",
	/* 0x14 */ "Hidden DOS 16-bit FAT <32M",
	/* 0x15 */ "Unknown",
	/* 0x16 */ "Hidden DOS 16-bit FAT >=32M",
	/* 0x17 */ "Hidden IFS (e.g., HPFS)",
	/* 0x18 */ "AST SmartSleep Partition",
	/* 0x19 */ "Unused (Claimed for Willowtech Photon COS)",
	/* 0x1a */ "Unknown",
	/* 0x1b */ "Hidden WIN95 OSR2 32-bit FAT",
	/* 0x1c */ "Hidden WIN95 OSR2 32-bit FAT, LBA-mapped",
	/* 0x1d */ "Unknown",
	/* 0x1e */ "Hidden WIN95 16-bit FAT, LBA-mapped",
	/* 0x1f */ "Unknown",
	/* 0x20 */ "Unused",
	/* 0x21 */ "Unused",
	/* 0x22 */ "Unused",
	/* 0x23 */ "Reserved",
	/* 0x24 */ "NEC DOS 3.x",
	/* 0x25 */ "Unknown",
	/* 0x26 */ "Reserved",
	/* 0x27 */ "Unknown",
	/* 0x28 */ "Unknown",
	/* 0x29 */ "Unknown",
	/* 0x2a */ "Unknown",
	/* 0x2b */ "Unknown",
	/* 0x2c */ "Unknown",
	/* 0x2d */ "Unknown",
	/* 0x2e */ "Unknown",
	/* 0x2f */ "Unknown",
	/* 0x30 */ "Unknown",
	/* 0x31 */ "Reserved",
	/* 0x32 */ "NOS",
	/* 0x33 */ "Reserved",
	/* 0x34 */ "Reserved",
	/* 0x35 */ "JFS on OS/2 or eCS",
	/* 0x36 */ "Reserved",
	/* 0x37 */ "Unknown",
	/* 0x38 */ "THEOS ver 3.2 2gb partition",
	/* 0x39 */ "THEOS ver 4 spanned partition",
	/* 0x3a */ "THEOS ver 4 4gb partition",
	/* 0x3b */ "THEOS ver 4 extended partition",
	/* 0x3c */ "PartitionMagic recovery partition",
	/* 0x3d */ "Hidden NetWare",
	/* 0x3e */ "Unknown",
	/* 0x3f */ "Unknown",
	/* 0x40 */ "Venix 80286",
	/* 0x41 */ "PPC PReP (Power PC Reference Platform) Boot",
	/* 0x42 */ "Windows 2000 marker",
	/* 0x43 */ "Linux native (sharing disk with DRDOS)",
	/* 0x44 */ "GoBack partition",
	/* 0x45 */ "EUMEL/Elan",
	/* 0x46 */ "EUMEL/Elan",
	/* 0x47 */ "EUMEL/Elan",
	/* 0x48 */ "EUMEL/Elan",
	/* 0x49 */ "Unknown",
	/* 0x4a */ "ALFS/THIN lightweight filesystem for DOS",
	/* 0x4b */ "Unknown",
	/* 0x4c */ "Oberon partition",
	/* 0x4d */ "QNX4.x",
	/* 0x4e */ "QNX4.x 2nd part",
	/* 0x4f */ "Oberon partition",
	/* 0x50 */ "Native Oberon (alt)",
	/* 0x51 */ "Novell",
	/* 0x52 */ "Microport SysV/AT",
	/* 0x53 */ "Disk Manager 6.0 Aux3",
	/* 0x54 */ "Disk Manager 6.0 Dynamic Drive Overlay",
	/* 0x55 */ "EZ-Drive",
	/* 0x56 */ "DM converted to EZ-BIOS",
	/* 0x57 */ "VNDI Partition",
	/* 0x58 */ "Unknown",
	/* 0x59 */ "Unknown",
	/* 0x5a */ "Unknown",
	/* 0x5b */ "Unknown",
	/* 0x5c */ "Priam EDisk",
	/* 0x5d */ "Unknown",
	/* 0x5e */ "Unknown",
	/* 0x5f */ "Unknown",
	/* 0x60 */ "Unknown",
	/* 0x61 */ "SpeedStor",
	/* 0x62 */ "Unknown",
	/* 0x63 */ "Unix System V (SCO, ISC Unix, UnixWare, ...), Mach, GNU Hurd",
	/* 0x64 */ "Novell Netware 286, 2.xx",
	/* 0x65 */ "Novell Netware 386, 3.xx or 4.xx",
	/* 0x66 */ "Novell Netware SMS Partition",
	/* 0x67 */ "Novell",
	/* 0x68 */ "Novell",
	/* 0x69 */ "Novell Netware 5+, Novell Netware NSS Partition",
	/* 0x6a */ "Unknown",
	/* 0x6b */ "Unknown",
	/* 0x6c */ "Unknown",
	/* 0x6d */ "Unknown",
	/* 0x6e */ "Unknown",
	/* 0x6f */ "Unknown",
	/* 0x70 */ "DiskSecure Multi-Boot",
	/* 0x71 */ "Reserved",
	/* 0x72 */ "Unknown",
	/* 0x73 */ "Reserved",
	/* 0x74 */ "Scramdisk partition",
	/* 0x75 */ "IBM PC/IX",
	/* 0x76 */ "Reserved",
	/* 0x77 */ "VNDI Partition",
	/* 0x78 */ "XOSL FS",
	/* 0x79 */ "Unknown",
	/* 0x7a */ "Unknown",
	/* 0x7b */ "Unknown",
	/* 0x7c */ "Unknown",
	/* 0x7d */ "Unknown",
	/* 0x7e */ "Unknown",
	/* 0x7f */ "Unknown",
	/* 0x80 */ "MINIX until 1.4a",
	/* 0x81 */ "Mitac disk manager",
	/* 0x82 */ "Linux swap",
	/* 0x83 */ "Linux native (usually ext2fs)",
	/* 0x84 */ "Hibernation partition",
	/* 0x85 */ "Linux extended partition",
	/* 0x86 */ "NTFS volume set",
	/* 0x87 */ "NTFS volume set",
	/* 0x88 */ "Unknown",
	/* 0x89 */ "Unknown",
	/* 0x8a */ "Linux Kernel Partition (used by AiR-BOOT)",
	/* 0x8b */ "Legacy Fault Tolerant FAT32 volume",
	/* 0x8c */ "Legacy Fault Tolerant FAT32 volume using BIOS extd INT 13h",
	/* 0x8d */ "Free FDISK hidden Primary DOS FAT12 partitition",
	/* 0x8e */ "Linux Logical Volume Manager partition",
	/* 0x8f */ "Unknown",
	/* 0x90 */ "Free FDISK hidden Primary DOS FAT16 partitition",
	/* 0x91 */ "Free FDISK hidden DOS extended partitition",
	/* 0x92 */ "Free FDISK hidden Primary DOS large FAT16 partitition",
	/* 0x93 */ "Amoeba",
	/* 0x94 */ "Amoeba bad block table",
	/* 0x95 */ "MIT EXOPC native partitions",
	/* 0x96 */ "Unknown",
	/* 0x97 */ "Free FDISK hidden Primary DOS FAT32 partitition",
	/* 0x98 */ "Free FDISK hidden Primary DOS FAT32 partitition (LBA)",
	/* 0x99 */ "DCE376 logical drive",
	/* 0x9a */ "Free FDISK hidden Primary DOS FAT16 partitition (LBA)",
	/* 0x9b */ "Free FDISK hidden DOS extended partitition (LBA)",
	/* 0x9c */ "Unknown",
	/* 0x9d */ "Unknown",
	/* 0x9e */ "Unknown",
	/* 0x9f */ "BSD/OS",
	/* 0xa0 */ "Laptop hibernation partition",
	/* 0xa1 */ "HP Volume Expansion (SpeedStor variant)",
	/* 0xa2 */ "Unknown",
	/* 0xa3 */ "Reserved",
	/* 0xa4 */ "Reserved",
	/* 0xa5 */ "BSD/386, 386BSD, NetBSD, FreeBSD",
	/* 0xa6 */ "OpenBSD",
	/* 0xa7 */ "NEXTSTEP",
	/* 0xa8 */ "Mac OS-X",
	/* 0xa9 */ "NetBSD",
	/* 0xaa */ "Olivetti Fat 12 1.44Mb Service Partition",
	/* 0xab */ "GO! partition",
	/* 0xac */ "Unknown",
	/* 0xad */ "Unknown",
	/* 0xae */ "ShagOS filesystem",
	/* 0xaf */ "ShagOS swap partition",
	/* 0xb0 */ "BootStar Dummy",
	/* 0xb1 */ "Reserved",
	/* 0xb2 */ "Unknown",
	/* 0xb3 */ "Reserved",
	/* 0xb4 */ "Reserved",
	/* 0xb5 */ "Unknown",
	/* 0xb6 */ "Reserved",
	/* 0xb7 */ "BSDI BSD/386 filesystem",
	/* 0xb8 */ "BSDI BSD/386 swap partition",
	/* 0xb9 */ "Unknown",
	/* 0xba */ "Unknown",
	/* 0xbb */ "Boot Wizard hidden",
	/* 0xbc */ "Unknown",
	/* 0xbd */ "Unknown",
	/* 0xbe */ "Solaris 8 boot partition",
	/* 0xbf */ "Unknown",
	/* 0xc0 */ "NTFT Partition",
	/* 0xc1 */ "DRDOS/secured (FAT-12)",
	/* 0xc2 */ "Hidden Linux",
	/* 0xc3 */ "Hidden Linux swap",
	/* 0xc4 */ "DRDOS/secured (FAT-16, < 32M)",
	/* 0xc5 */ "DRDOS/secured (extended)",
	/* 0xc6 */ "Windows NT corrupted FAT16 volume/stripe set",
	/* 0xc7 */ "Syrinx boot",
	/* 0xc8 */ "Reserved for DR-DOS 8.0+",
	/* 0xc9 */ "Reserved for DR-DOS 8.0+",
	/* 0xca */ "Reserved for DR-DOS 8.0+",
	/* 0xcb */ "reserved for DRDOS/secured (FAT32)",
	/* 0xcc */ "reserved for DRDOS/secured (FAT32, LBA)",
	/* 0xcd */ "CTOS Memdump?",
	/* 0xce */ "reserved for DRDOS/secured (FAT16, LBA)",
	/* 0xcf */ "Unknown",
	/* 0xd0 */ "REAL/32 secure big partition",
	/* 0xd1 */ "Old Multiuser DOS secured FAT12",
	/* 0xd2 */ "Unknown",
	/* 0xd3 */ "Unknown",
	/* 0xd4 */ "Old Multiuser DOS secured FAT16 <32M",
	/* 0xd5 */ "Old Multiuser DOS secured extended partition",
	/* 0xd6 */ "Old Multiuser DOS secured FAT16 >=32M",
	/* 0xd7 */ "Unknown",
	/* 0xd8 */ "CP/M-86",
	/* 0xd9 */ "Unknown",
	/* 0xda */ "Non-FS Data",
	/* 0xdb */ "KDG Telemetry SCPU boot",
	/* 0xdc */ "Unknown",
	/* 0xdd */ "Hidden CTOS Memdump?",
	/* 0xde */ "Dell PowerEdge Server utilities (FAT fs)",
	/* 0xdf */ "BootIt EMBRM",
	/* 0xe0 */ "Reserved by STMicroelectronics for a filesystem called ST AVFS.",
	/* 0xe1 */ "DOS access or SpeedStor 12-bit FAT extended partition",
	/* 0xe2 */ "Unknown",
	/* 0xe3 */ "DOS R/O or SpeedStor",
	/* 0xe4 */ "SpeedStor 16-bit FAT extended partition < 1024 cyl.",
	/* 0xe5 */ "Reserved",
	/* 0xe6 */ "Reserved",
	/* 0xe7 */ "Unknown",
	/* 0xe8 */ "Unknown",
	/* 0xe9 */ "Unknown",
	/* 0xea */ "Unknown",
	/* 0xeb */ "BFS (aka BeFS)",
	/* 0xec */ "Unknown",
	/* 0xed */ "Reserved for Matthias Paul's Sprytix",
	/* 0xee */ "Indication that this legacy MBR is followed by an EFI header",
	/* 0xef */ "Partition that contains an EFI file system",
	/* 0xf0 */ "Linux/PA-RISC boot loader",
	/* 0xf1 */ "SpeedStor",
	/* 0xf2 */ "DOS 3.3+ secondary partition (Powerquest writes: Unisys DOS with logical sectored FAT)",
	/* 0xf3 */ "Reserved (Powerquest writes: Storage Dimensions SpeedStor)",
	/* 0xf4 */ "Prologue single-volume partition",
	/* 0xf5 */ "Prologue multi-volume partition",
	/* 0xf6 */ "Reserved (Powerquest writes: Storage Dimensions SpeedStor. )",
	/* 0xf7 */ "Unknown",
	/* 0xf8 */ "Unknown",
	/* 0xf9 */ "Unknown",
	/* 0xfa */ "Bochs",
	/* 0xfb */ "VMware File System partition",
	/* 0xfc */ "VMware Swap partition",
	/* 0xfd */ "Linux raid partition with autodetect using persistent superblock (Powerquest writes: Reserved for FreeDOS)",
	/* 0xfe */ "Linux Logical Volume Manager partition (old)",
	/* 0xff */ "Xenix Bad Block Table",
};
