// Source: http://www.osdever.net/documents/partitiontypes.php

const char *system_ids[][256] = {
	/* 0x00 */ { "Unknown", 0 },
	/* 0x01 */ { "DOS 12-bit fat", 0 },
	/* 0x02 */ { "XENIX root", 0 },
	/* 0x03 */ { "XENIX /usr", 0 },
	/* 0x04 */ { "DOS 3.0+ 16-bit FAT (up to 32M)", 0 },
	/* 0x05 */ { "DOS 3.3+ Extended Partition", 0 },
	/* 0x06 */ { "DOS 3.31+ 16-bit FAT (over 32M)", 0 },
	/* 0x07 */ { "OS/2 IFS (e.g., HPFS)", "Advanced Unix", "Windows NT NTFS", "QNX2.x (pre-1988)", 0 },
	/* 0x08 */ { "OS/2 (v1.0-1.3 only)", "AIX boot partition", "SplitDrive", "DELL partition spanning multiple drives", "Commodore DOS", "QNX 1.x and 2.x ('qny')", 0 },
	/* 0x09 */ { "AIX data partition", "Coherent filesystem", "QNX 1.x and 2.x ('qnz')", 0 },
	/* 0x0a */ { "OS/2 Boot Manager", "Coherent swap partition", "OPUS", 0 },
	/* 0x0b */ { "WIN95 OSR2 32-bit FAT", 0 },
	/* 0x0c */ { "WIN95 OSR2 32-bit FAT, LBA-mapped", 0 },
	/* 0x0d */ { "Unknown", 0 },
	/* 0x0e */ { "WIN95: DOS 16-bit FAT, LBA-mapped", 0 },
	/* 0x0f */ { "WIN95: Extended partition, LBA-mapped", 0 },
	/* 0x10 */ { "OPUS (?)", 0 },
	/* 0x11 */ { "Hidden DOS 12-bit FAT", 0 },
	/* 0x12 */ { "Compaq config partition", 0 },
	/* 0x13 */ { "Unknown", 0 },
	/* 0x14 */ { "Hidden DOS 16-bit FAT <32M", 0 },
	/* 0x15 */ { "Unknown", 0 },
	/* 0x16 */ { "Hidden DOS 16-bit FAT >=32M", 0 },
	/* 0x17 */ { "Hidden IFS (e.g., HPFS)", 0 },
	/* 0x18 */ { "AST SmartSleep Partition", 0 },
	/* 0x19 */ { "Unused (Claimed for Willowtech Photon COS)", 0 },
	/* 0x1a */ { "Unknown", 0 },
	/* 0x1b */ { "Hidden WIN95 OSR2 32-bit FAT", 0 },
	/* 0x1c */ { "Hidden WIN95 OSR2 32-bit FAT, LBA-mapped", 0 },
	/* 0x1d */ { "Unknown", 0 },
	/* 0x1e */ { "Hidden WIN95 16-bit FAT, LBA-mapped", 0 },
	/* 0x1f */ { "Unknown", 0 },
	/* 0x20 */ { "Unused", 0 },
	/* 0x21 */ { "Reserved", "Unused", 0 },
	/* 0x22 */ { "Unused", 0 },
	/* 0x23 */ { "Reserved", 0 },
	/* 0x24 */ { "NEC DOS 3.x", 0 },
	/* 0x25 */ { "Unknown", 0 },
	/* 0x26 */ { "Reserved", 0 },
	/* 0x27 */ { "Unknown", 0 },
	/* 0x28 */ { "Unknown", 0 },
	/* 0x29 */ { "Unknown", 0 },
	/* 0x2a */ { "Unknown", 0 },
	/* 0x2b */ { "Unknown", 0 },
	/* 0x2c */ { "Unknown", 0 },
	/* 0x2d */ { "Unknown", 0 },
	/* 0x2e */ { "Unknown", 0 },
	/* 0x2f */ { "Unknown", 0 },
	/* 0x30 */ { "Unknown", 0 },
	/* 0x31 */ { "Reserved", 0 },
	/* 0x32 */ { "NOS", 0 },
	/* 0x33 */ { "Reserved", 0 },
	/* 0x34 */ { "Reserved", 0 },
	/* 0x35 */ { "JFS on OS/2 or eCS", 0 },
	/* 0x36 */ { "Reserved", 0 },
	/* 0x37 */ { "Unknown", 0 },
	/* 0x38 */ { "THEOS ver 3.2 2gb partition", 0 },
	/* 0x39 */ { "Plan 9 partition", "THEOS ver 4 spanned partition", 0 },
	/* 0x3a */ { "THEOS ver 4 4gb partition", 0 },
	/* 0x3b */ { "THEOS ver 4 extended partition", 0 },
	/* 0x3c */ { "PartitionMagic recovery partition", 0 },
	/* 0x3d */ { "Hidden NetWare", 0 },
	/* 0x3e */ { "Unknown", 0 },
	/* 0x3f */ { "Unknown", 0 },
	/* 0x40 */ { "Venix 80286", 0 },
	/* 0x41 */ { "Linux/MINIX (sharing disk with DRDOS)", "Personal RISC Boot", "PPC PReP (Power PC Reference Platform) Boot", 0 },
	/* 0x42 */ { "Linux swap (sharing disk with DRDOS)", "SFS (Secure Filesystem)", "Windows 2000 marker", 0 },
	/* 0x43 */ { "Linux native (sharing disk with DRDOS)", 0 },
	/* 0x44 */ { "GoBack partition", 0 },
	/* 0x45 */ { "Boot-US boot manager", "Priam", "EUMEL/Elan", 0 },
	/* 0x46 */ { "EUMEL/Elan", 0 },
	/* 0x47 */ { "EUMEL/Elan", 0 },
	/* 0x48 */ { "EUMEL/Elan", 0 },
	/* 0x49 */ { "Unknown", 0 },
	/* 0x4a */ { "AdaOS Aquila (Default)", "ALFS/THIN lightweight filesystem for DOS", 0 },
	/* 0x4b */ { "Unknown", 0 },
	/* 0x4c */ { "Oberon partition", 0 },
	/* 0x4d */ { "QNX4.x", 0 },
	/* 0x4e */ { "QNX4.x 2nd part", 0 },
	/* 0x4f */ { "QNX4.x 3rd part", "Oberon partition", 0 },
	/* 0x50 */ { "OnTrack Disk Manager (older versions) RO", "Lynx RTOS", "Native Oberon (alt)", 0 },
	/* 0x51 */ { "OnTrack Disk Manager RW (DM6 Aux1)", "Novell", 0 },
	/* 0x52 */ { "CP/M", "Microport SysV/AT", 0 },
	/* 0x53 */ { "Disk Manager 6.0 Aux3", 0 },
	/* 0x54 */ { "Disk Manager 6.0 Dynamic Drive Overlay", 0 },
	/* 0x55 */ { "EZ-Drive", 0 },
	/* 0x56 */ { "Golden Bow VFeature Partitioned Volume.", "DM converted to EZ-BIOS", 0 },
	/* 0x57 */ { "DrivePro", "VNDI Partition", 0 },
	/* 0x58 */ { "Unknown", 0 },
	/* 0x59 */ { "Unknown", 0 },
	/* 0x5a */ { "Unknown", 0 },
	/* 0x5b */ { "Unknown", 0 },
	/* 0x5c */ { "Priam EDisk", 0 },
	/* 0x5d */ { "Unknown", 0 },
	/* 0x5e */ { "Unknown", 0 },
	/* 0x5f */ { "Unknown", 0 },
	/* 0x60 */ { "Unknown", 0 },
	/* 0x61 */ { "SpeedStor", 0 },
	/* 0x62 */ { "Unknown", 0 },
	/* 0x63 */ { "Unix System V (SCO, ISC Unix, UnixWare, ...), Mach, GNU Hurd", 0 },
	/* 0x64 */ { "PC-ARMOUR protected partition", "Novell Netware 286, 2.xx", 0 },
	/* 0x65 */ { "Novell Netware 386, 3.xx or 4.xx", 0 },
	/* 0x66 */ { "Novell Netware SMS Partition", 0 },
	/* 0x67 */ { "Novell", 0 },
	/* 0x68 */ { "Novell", 0 },
	/* 0x69 */ { "Novell Netware 5+, Novell Netware NSS Partition", 0 },
	/* 0x6a */ { "Unknown", 0 },
	/* 0x6b */ { "Unknown", 0 },
	/* 0x6c */ { "Unknown", 0 },
	/* 0x6d */ { "Unknown", 0 },
	/* 0x6e */ { "Unknown", 0 },
	/* 0x6f */ { "Unknown", 0 },
	/* 0x70 */ { "DiskSecure Multi-Boot", 0 },
	/* 0x71 */ { "Reserved", 0 },
	/* 0x72 */ { "Unknown", 0 },
	/* 0x73 */ { "Reserved", 0 },
	/* 0x74 */ { "Reserved", "Scramdisk partition", 0 },
	/* 0x75 */ { "IBM PC/IX", 0 },
	/* 0x76 */ { "Reserved", 0 },
	/* 0x77 */ { "M2FS/M2CS partition", "VNDI Partition", 0 },
	/* 0x78 */ { "XOSL FS", 0 },
	/* 0x79 */ { "Unknown", 0 },
	/* 0x7a */ { "Unknown", 0 },
	/* 0x7b */ { "Unknown", 0 },
	/* 0x7c */ { "Unknown", 0 },
	/* 0x7d */ { "Unknown", 0 },
	/* 0x7e */ { "Unknown", 0 },
	/* 0x7f */ { "Unknown", 0 },
	/* 0x80 */ { "MINIX until 1.4a", 0 },
	/* 0x81 */ { "MINIX since 1.4b, early Linux", "Mitac disk manager", 0 },
	/* 0x82 */ { "Prime", "Solaris x86", "Linux swap", 0 },
	/* 0x83 */ { "Linux native (usually ext2fs)", 0 },
	/* 0x84 */ { "OS/2 hidden C: drive", "Hibernation partition", 0 },
	/* 0x85 */ { "Linux extended partition", 0 },
	/* 0x86 */ { "Old Linux RAID partition superblock", "NTFS volume set", 0 },
	/* 0x87 */ { "NTFS volume set", 0 },
	/* 0x88 */ { "Unknown", 0 },
	/* 0x89 */ { "Unknown", 0 },
	/* 0x8a */ { "Linux Kernel Partition (used by AiR-BOOT)", 0 },
	/* 0x8b */ { "Legacy Fault Tolerant FAT32 volume", 0 },
	/* 0x8c */ { "Legacy Fault Tolerant FAT32 volume using BIOS extd INT 13h", 0 },
	/* 0x8d */ { "Free FDISK hidden Primary DOS FAT12 partitition", 0 },
	/* 0x8e */ { "Linux Logical Volume Manager partition", 0 },
	/* 0x8f */ { "Unknown", 0 },
	/* 0x90 */ { "Free FDISK hidden Primary DOS FAT16 partitition", 0 },
	/* 0x91 */ { "Free FDISK hidden DOS extended partitition", 0 },
	/* 0x92 */ { "Free FDISK hidden Primary DOS large FAT16 partitition", 0 },
	/* 0x93 */ { "Hidden Linux native partition", "Amoeba", 0 },
	/* 0x94 */ { "Amoeba bad block table", 0 },
	/* 0x95 */ { "MIT EXOPC native partitions", 0 },
	/* 0x96 */ { "Unknown", 0 },
	/* 0x97 */ { "Free FDISK hidden Primary DOS FAT32 partitition", 0 },
	/* 0x98 */ { "Free FDISK hidden Primary DOS FAT32 partitition (LBA)", 0 },
	/* 0x99 */ { "DCE376 logical drive", 0 },
	/* 0x9a */ { "Free FDISK hidden Primary DOS FAT16 partitition (LBA)", 0 },
	/* 0x9b */ { "Free FDISK hidden DOS extended partitition (LBA)", 0 },
	/* 0x9c */ { "Unknown", 0 },
	/* 0x9d */ { "Unknown", 0 },
	/* 0x9e */ { "Unknown", 0 },
	/* 0x9f */ { "BSD/OS", 0 },
	/* 0xa0 */ { "Laptop hibernation partition", 0 },
	/* 0xa1 */ { "Laptop hibernation partition", "HP Volume Expansion (SpeedStor variant)", 0 },
	/* 0xa2 */ { "Unknown", 0 },
	/* 0xa3 */ { "Reserved", 0 },
	/* 0xa4 */ { "Reserved", 0 },
	/* 0xa5 */ { "BSD/386, 386BSD, NetBSD, FreeBSD", 0 },
	/* 0xa6 */ { "OpenBSD", 0 },
	/* 0xa7 */ { "NEXTSTEP", 0 },
	/* 0xa8 */ { "Mac OS-X", 0 },
	/* 0xa9 */ { "NetBSD", 0 },
	/* 0xaa */ { "Olivetti Fat 12 1.44Mb Service Partition", 0 },
	/* 0xab */ { "Mac OS-X Boot partition", "GO! partition", 0 },
	/* 0xac */ { "Unknown", 0 },
	/* 0xad */ { "Unknown", 0 },
	/* 0xae */ { "ShagOS filesystem", 0 },
	/* 0xaf */ { "ShagOS swap partition", 0 },
	/* 0xb0 */ { "BootStar Dummy", 0 },
	/* 0xb1 */ { "Reserved", 0 },
	/* 0xb2 */ { "Unknown", 0 },
	/* 0xb3 */ { "Reserved", 0 },
	/* 0xb4 */ { "Reserved", 0 },
	/* 0xb5 */ { "Unknown", 0 },
	/* 0xb6 */ { "Reserved", 0 },
	/* 0xb7 */ { "BSDI BSD/386 filesystem", 0 },
	/* 0xb8 */ { "BSDI BSD/386 swap partition", 0 },
	/* 0xb9 */ { "Unknown", 0 },
	/* 0xba */ { "Unknown", 0 },
	/* 0xbb */ { "Boot Wizard hidden", 0 },
	/* 0xbc */ { "Unknown", 0 },
	/* 0xbd */ { "Unknown", 0 },
	/* 0xbe */ { "Solaris 8 boot partition", 0 },
	/* 0xbf */ { "Unknown", 0 },
	/* 0xc0 */ { "CTOS", "REAL/32 secure small partition", "NTFT Partition", 0 },
	/* 0xc1 */ { "DRDOS/secured (FAT-12)", 0 },
	/* 0xc2 */ { "Reserved for DR-DOS 7+", "Hidden Linux", 0 },
	/* 0xc3 */ { "Hidden Linux swap", 0 },
	/* 0xc4 */ { "DRDOS/secured (FAT-16, < 32M)", 0 },
	/* 0xc5 */ { "DRDOS/secured (extended)", 0 },
	/* 0xc6 */ { "DRDOS/secured (FAT-16, >= 32M)", "Windows NT corrupted FAT16 volume/stripe set", 0 },
	/* 0xc7 */ { "Windows NT corrupted NTFS volume/stripe set", "Syrinx boot", 0 },
	/* 0xc8 */ { "Reserved for DR-DOS 8.0+", 0 },
	/* 0xc9 */ { "Reserved for DR-DOS 8.0+", 0 },
	/* 0xca */ { "Reserved for DR-DOS 8.0+", 0 },
	/* 0xcb */ { "reserved for DRDOS/secured (FAT32)", 0 },
	/* 0xcc */ { "reserved for DRDOS/secured (FAT32, LBA)", 0 },
	/* 0xcd */ { "CTOS Memdump?", 0 },
	/* 0xce */ { "reserved for DRDOS/secured (FAT16, LBA)", 0 },
	/* 0xcf */ { "Unknown", 0 },
	/* 0xd0 */ { "REAL/32 secure big partition", 0 },
	/* 0xd1 */ { "Old Multiuser DOS secured FAT12", 0 },
	/* 0xd2 */ { "Unknown", 0 },
	/* 0xd3 */ { "Unknown", 0 },
	/* 0xd4 */ { "Old Multiuser DOS secured FAT16 <32M", 0 },
	/* 0xd5 */ { "Old Multiuser DOS secured extended partition", 0 },
	/* 0xd6 */ { "Old Multiuser DOS secured FAT16 >=32M", 0 },
	/* 0xd7 */ { "Unknown", 0 },
	/* 0xd8 */ { "CP/M-86", 0 },
	/* 0xd9 */ { "Unknown", 0 },
	/* 0xda */ { "Non-FS Data", 0 },
	/* 0xdb */ { "Digital Research CP/M, Concurrent CP/M, Concurrent DOS", "CTOS (Convergent Technologies OS -Unisys)", "KDG Telemetry SCPU boot", 0 },
	/* 0xdc */ { "Unknown", 0 },
	/* 0xdd */ { "Hidden CTOS Memdump?", 0 },
	/* 0xde */ { "Dell PowerEdge Server utilities (FAT fs)", 0 },
	/* 0xdf */ { "DG/UX virtual disk manager partition", "BootIt EMBRM", 0 },
	/* 0xe0 */ { "Reserved by STMicroelectronics for a filesystem called ST AVFS", 0 },
	/* 0xe1 */ { "DOS access or SpeedStor 12-bit FAT extended partition", 0 },
	/* 0xe2 */ { "Unknown", 0 },
	/* 0xe3 */ { "DOS R/O or SpeedStor", 0 },
	/* 0xe4 */ { "SpeedStor 16-bit FAT extended partition < 1024 cyl", 0 },
	/* 0xe5 */ { "Tandy DOS with logical sectored FAT (According to Powerquest)", "Reserved", 0 },
	/* 0xe6 */ { "Reserved", 0 },
	/* 0xe7 */ { "Unknown", 0 },
	/* 0xe8 */ { "Unknown", 0 },
	/* 0xe9 */ { "Unknown", 0 },
	/* 0xea */ { "Unknown", 0 },
	/* 0xeb */ { "BFS (aka BeFS)", 0 },
	/* 0xec */ { "Unknown", 0 },
	/* 0xed */ { "Reserved for Matthias Paul's Sprytix", 0 },
	/* 0xee */ { "Indication that this legacy MBR is followed by an EFI header", 0 },
	/* 0xef */ { "Partition that contains an EFI file system", 0 },
	/* 0xf0 */ { "Linux/PA-RISC boot loader", 0 },
	/* 0xf1 */ { "SpeedStor", 0 },
	/* 0xf2 */ { "DOS 3.3+ secondary partition (Powerquest writes: Unisys DOS with logical sectored FAT)", 0 },
	/* 0xf3 */ { "Reserved (Powerquest writes: Storage Dimensions SpeedStor)", 0 },
	/* 0xf4 */ { "SpeedStor large partition", "Prologue single-volume partition", 0 },
	/* 0xf5 */ { "Prologue multi-volume partition", 0 },
	/* 0xf6 */ { "Reserved (Powerquest writes: Storage Dimensions SpeedStor)", 0 },
	/* 0xf7 */ { "Unknown", 0 },
	/* 0xf8 */ { "Unknown", 0 },
	/* 0xf9 */ { "Unknown", 0 },
	/* 0xfa */ { "Bochs", 0 },
	/* 0xfb */ { "VMware File System partition", 0 },
	/* 0xfc */ { "VMware Swap partition", 0 },
	/* 0xfd */ { "Linux raid partition with autodetect using persistent superblock (Powerquest writes: Reserved for FreeDOS)", 0 },
	/* 0xfe */ { "SpeedStor > 1024 cyl", "LANstep", "IBM PS/2 IML (Initial Microcode Load) partition, located at the end of the disk", "Windows NT Disk Administrator hidden partition", "Linux Logical Volume Manager partition (old)", 0 },
	/* 0xff */ { "Xenix Bad Block Table", 0 },
};
